name: fluttercon_2023_presentation
description: My cool presentation for the fluttercon 2023.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  intl_utils: ^2.8.1

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  assets:
    - assets/audio/
    - assets/fonts/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/l10n
  ouput_dir: lib/generated

flutter_gen:
  output: lib/generated/
  line_length: 80
